"""Exact outer-batch and optimizer-step accounting for DART training."""

from __future__ import annotations

import math
from dataclasses import dataclass


@dataclass(frozen=True)
class TrainingBatchPlan:
    dataset_size: int
    train_batch_size: int
    ppo_mini_batch_size: int
    world_size: int
    epochs: int = 1
    drop_last: bool = True
    rollout_n: int = 1

    def __post_init__(self) -> None:
        for name in (
            "dataset_size",
            "train_batch_size",
            "ppo_mini_batch_size",
            "world_size",
            "epochs",
            "rollout_n",
        ):
            if int(getattr(self, name)) <= 0:
                raise ValueError(f"{name} must be positive, got {getattr(self, name)!r}")
        if self.train_batch_size % self.world_size:
            raise ValueError("train_batch_size must be divisible by world_size")
        if self.ppo_mini_batch_size % self.world_size:
            raise ValueError("ppo_mini_batch_size must be divisible by world_size")
        if self.train_batch_size % self.ppo_mini_batch_size:
            raise ValueError("train_batch_size must be divisible by ppo_mini_batch_size")
        if not self.drop_last and self.final_batch_size % self.world_size:
            raise ValueError(
                "The retained final batch must be divisible by world_size so every DART rank "
                "executes the same number of cached-decode collectives"
            )

    @property
    def final_batch_size(self) -> int:
        remainder = self.dataset_size % self.train_batch_size
        return remainder or self.train_batch_size

    @property
    def outer_steps_per_epoch(self) -> int:
        if self.drop_last:
            return self.dataset_size // self.train_batch_size
        return math.ceil(self.dataset_size / self.train_batch_size)

    @property
    def samples_per_epoch(self) -> int:
        if self.drop_last:
            return self.outer_steps_per_epoch * self.train_batch_size
        return self.dataset_size

    @property
    def optimizer_steps_per_epoch(self) -> int:
        full_batches, remainder = divmod(self.dataset_size, self.train_batch_size)
        steps = full_batches * (self.train_batch_size // self.ppo_mini_batch_size)
        if remainder and not self.drop_last:
            # DataProto.split retains its final partial chunk.  A partial outer
            # batch therefore still performs one optimizer update when the
            # configured mini-batch equals the full outer batch, while
            # more general plans use the exact ceiling.
            steps += math.ceil(remainder / self.ppo_mini_batch_size)
        return steps

    @property
    def total_outer_steps(self) -> int:
        return self.outer_steps_per_epoch * self.epochs

    @property
    def total_optimizer_steps(self) -> int:
        return self.optimizer_steps_per_epoch * self.epochs

    @property
    def trajectories_per_full_outer_step(self) -> int:
        """Rollout trajectories generated by a full prompt batch."""

        return self.train_batch_size * self.rollout_n

    @property
    def trajectories_per_optimizer_step(self) -> int:
        """Trajectory count represented by one prompt-level PPO mini-batch."""

        return self.ppo_mini_batch_size * self.rollout_n

    @property
    def trajectories_per_epoch(self) -> int:
        return self.samples_per_epoch * self.rollout_n

    @property
    def total_trajectories(self) -> int:
        return self.trajectories_per_epoch * self.epochs

